import { useState, useEffect } from 'react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import type { VendorShipmentDeclaration } from '@/types';
import supabase from '@/supabaseClient';

interface VendorDeclarationFormProps {
  onSubmit: (data: VendorShipmentDeclaration & { userId?: string }) => void;
  onCancel: () => void;
  isLoading: boolean;
}

export default function VendorDeclarationForm({ onSubmit, onCancel, isLoading }: VendorDeclarationFormProps) {
  const [userId, setUserId] = useState<string | null>(null);
  const [formData, setFormData] = useState<VendorShipmentDeclaration>({
    itemName: '',
    quantity: 1,
    weight: 0,
    consigneeName: '',
    consigneeAddress: '',
    consigneeEmail: '',
    consigneePhone: '',
    hsCode: '',
  });

  // Get current user ID on mount
  useEffect(() => {
    async function getUserId() {
      const { data: { session } } = await supabase.auth.getSession();
      if (session?.user?.id) {
        setUserId(session.user.id);
      }
    }
    getUserId();
  }, []);

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    onSubmit({ ...formData, userId: userId || undefined });
  };

  const handleChange = (field: keyof VendorShipmentDeclaration, value: string | number) => {
    setFormData(prev => ({
      ...prev,
      [field]: value
    }));
  };

  return (
    <form onSubmit={handleSubmit} className="space-y-6">
      {/* Vendor Declaration ID will be auto-generated by the system */}
      <Card className="bg-blue-50 border-blue-200">
        <CardHeader>
          <CardTitle className="text-blue-900">📋 About Vendor Declaration ID</CardTitle>
        </CardHeader>
        <CardContent>
          <div className="space-y-2 text-sm text-blue-700">
            <p className="font-semibold">
              A unique <span className="font-mono bg-blue-100 px-1.5 py-0.5 rounded">Vendor Declaration ID (VD-XXXX-XXXXX)</span> will be automatically assigned after submission.
            </p>
            <p>
              <strong>Use this ID to:</strong> Check if your shipment has been received and processed by the shipping company.
            </p>
            <p className="text-xs">
              Note: Once dispatched to customers, a separate <span className="font-mono">Tracking ID (TRK-XXXX)</span> will be created for customer tracking.
            </p>
          </div>
        </CardContent>
      </Card>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        <div className="space-y-4">
          <h3 className="text-lg font-medium text-gray-900">Item Information</h3>
          
          <div>
            <Label htmlFor="itemName">Item Name *</Label>
            <Input
              id="itemName"
              type="text"
              required
              value={formData.itemName}
              onChange={(e) => handleChange('itemName', e.target.value)}
              placeholder="Electronic gadgets"
              className="mt-1"
            />
          </div>

          <div className="grid grid-cols-2 gap-4">
            <div>
              <Label htmlFor="quantity">Quantity *</Label>
              <Input
                id="quantity"
                type="number"
                required
                min="1"
                value={formData.quantity}
                onChange={(e) => handleChange('quantity', parseInt(e.target.value))}
                className="mt-1"
              />
            </div>
            <div>
              <Label htmlFor="weight">Weight (kg) *</Label>
              <Input
                id="weight"
                type="number"
                required
                min="0"
                step="0.1"
                value={formData.weight}
                onChange={(e) => handleChange('weight', parseFloat(e.target.value))}
                className="mt-1"
              />
            </div>
          </div>

          <div>
            <Label htmlFor="hsCode">HS Code (Optional)</Label>
            <Input
              id="hsCode"
              type="text"
              value={formData.hsCode}
              onChange={(e) => handleChange('hsCode', e.target.value)}
              placeholder="8517.12.00"
              className="mt-1"
            />
          </div>
        </div>

        <div className="space-y-4">
          <h3 className="text-lg font-medium text-gray-900">Consignee Information</h3>
          
          <div>
            <Label htmlFor="consigneeName">Full Name *</Label>
            <Input
              id="consigneeName"
              type="text"
              required
              value={formData.consigneeName}
              onChange={(e) => handleChange('consigneeName', e.target.value)}
              placeholder="John Doe"
              className="mt-1"
            />
          </div>

          <div>
            <Label htmlFor="consigneeEmail">Email Address *</Label>
            <Input
              id="consigneeEmail"
              type="email"
              required
              value={formData.consigneeEmail}
              onChange={(e) => handleChange('consigneeEmail', e.target.value)}
              placeholder="john@example.com"
              className="mt-1"
            />
          </div>

          <div>
            <Label htmlFor="consigneePhone">Phone Number *</Label>
            <Input
              id="consigneePhone"
              type="tel"
              required
              value={formData.consigneePhone}
              onChange={(e) => handleChange('consigneePhone', e.target.value)}
              placeholder="+1 555 123 4567"
              className="mt-1"
            />
          </div>

          <div>
            <Label htmlFor="consigneeAddress">Delivery Address *</Label>
            <Textarea
              id="consigneeAddress"
              required
              value={formData.consigneeAddress}
              onChange={(e) => handleChange('consigneeAddress', e.target.value)}
              placeholder="123 Main St, City, State, Country"
              rows={3}
              className="mt-1"
            />
          </div>
        </div>
      </div>

      <div className="flex justify-end space-x-4 pt-6 border-t">
        <Button type="button" variant="outline" onClick={onCancel}>
          Cancel
        </Button>
        <Button type="submit" disabled={isLoading}>
          {isLoading ? 'Creating Declaration...' : 'Create Declaration'}
        </Button>
      </div>
    </form>
  );
}
